apiVersion: v1
kind: Service
metadata:
  name: best-node-selector
  namespace: graph-foundry-system
  labels:
    app: best-node-selector
spec:
  type: ClusterIP
  selector:
    app: best-node-selector
  ports:
    - name: http
      port: 9000
      targetPort: 9000
