apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - rbac.yaml
  - best-node-selector-deployment.yaml
  - best-node-selector-service.yaml
  - scheduler-deployment.yaml
