apiVersion: v1
kind: ServiceAccount
metadata:
  name: best-node-selector
  namespace: graph-foundry-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: best-node-selector
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: best-node-selector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: best-node-selector
subjects:
  - kind: ServiceAccount
    name: best-node-selector
    namespace: graph-foundry-system
