apiVersion: v1
kind: Service
metadata:
  name: service-graph-engine
  namespace: graph-foundry-system
  labels:
    app: service-graph-engine
spec:
  type: ClusterIP
  selector:
    app: service-graph-engine
  ports:
    - name: http
      port: 3000
      targetPort: 3000
